version: "3.5"

services:
  courses-service:
    container_name: courses-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: courses-service
    ports:
      - "8083:8080"
    depends_on:
      - courses-service_database
    networks:
      - noodlee-system-network

  courses-service_database:
    container_name: courses-service_database
    image: postgres:9.6
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: N>4yQ5^N#7%;vGR]
      POSTGRES_DB: courses
    volumes:
      - courses-service_database-volume:/var/lib/postgresql/courses
    networks:
      - noodlee-system-network

networks:
  noodlee-system-network:
    name: noodlee-system-network
    driver: bridge
    
volumes:
  courses-service_database-volume:
